[FINDPLACE DEBUG] input='赤坂氷川神社' locationbias=None
[FINDPLACE DEBUG] input='赤坂氷川神社' locationbias=None
[FINDPLACE DEBUG] input='赤坂氷川神社' locationbias=None
F
=================================== FAILURES ===================================
__________________ test_api_accepts_area_string_and_shortens ___________________

client = <django.test.client.Client object at 0x1183a7890>
endpoint_path = '/api/concierge/plan/'
req_history = [('https://maps.googleapis.com/maps/api/place/findplacefromtext/json', {'fields': 'place_id,name,formatted_address,geo...{'fields': 'place_id,name,formatted_address,geometry', 'input': '赤坂氷川神社', 'inputtype': 'textquery', 'key': None, ...})]

    @pytest.mark.django_db
    def test_api_accepts_area_string_and_shortens(client, endpoint_path, req_history):
        payload = {
            "query": "縁結び 徒歩",
            "area": "港区赤坂",
            "candidates": [{"name": "赤坂氷川神社"}],
        }
        res = client.post(endpoint_path, data=json.dumps(payload), content_type="application/json")
        assert res.status_code == 200
>       data = res.json()["data"]["recommendations"][0]
E       IndexError: list index out of range

temples/tests/test_concierge.py:72: IndexError
=========================== short test summary info ============================
FAILED temples/tests/test_concierge.py::test_api_accepts_area_string_and_shortens
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
